config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /es|en/ do
    mount Ckeditor::Engine => '/ckeditor'
    devise_for :admins

    root 'posts#index'
    resources :posts
    resources :tags, only: [:index, :show]

    get '*path', to: 'posts#not_found'
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 140 }
  validates :body, presence: true
  translates :title, :body
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_taggable_on :tags

  scope :get_all_with_tags_translations, -> { includes(:tags, :translations).order(created_at: :desc) }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  scope :get_all, -> { order(:name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def set_locale
    locale = params[:locale]
    I18n.locale = (%w[es en].include?locale) ? locale : I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? params[:locale] : I18n.locale }
  end

  protected

  # configure permitted parameters for devise
  def configure_permitted_parameters
    added_attrs = %i[email password password_confirmation remember_me avatar avatar_cache]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show not_found]
  before_action :find_post, only: %i[edit update show destroy]
  before_action :tags, only: %i[new edit]

  def index
    @posts = Post.get_all_with_tags_translations
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = I18n.t('forms.messages.success')
      redirect_to post_path(@post)
    else
      flash.now[:alert] = I18n.t('forms.messages.error')
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = I18n.t('forms.messages.success')
      redirect_to post_path(@post)
    else
      flash.now[:alert] = I18n.t('forms.messages.error')
      render :edit
    end
  end

  def destroy
    @post.destroy

    flash[:notice] = I18n.t('forms.messages.success')
    redirect_to posts_path
  end

  def not_found; end

  private

  def post_params
    params.require(:post).permit(:title, :body, :tag_list)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = t('extras.post_not_found')
    redirect_to posts_path
  end

  def tags
    @tags = Tag.get_all.pluck(:name).join(', ')
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @posts = Post.tagged_with(@tag.name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def locale
    link_text = t('extras.en_version')
    switch_locale = :en

    if I18n.locale == :en
      link_text = t('extras.es_version')
      switch_locale = :es
    end

    link = link_to link_text, root_path(locale: switch_locale)

    link.html_safe
  end

  def social_links(url, icon)
    link_to url, target: '_blank' do
      fa_icon icon, class: 'fa-2x'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag), class: 'tag' %>

app/views/admins/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <% if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Cris' Blog", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('extras.home'), root_path %></li>
        <% if admin_signed_in? %>
          <li><%= link_to t('activerecord.attributes.post.new'), new_post_path %></li>
          <li><%= link_to t('extras.logout'), destroy_admin_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to t('extras.login'), new_admin_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <% if Rails.env.production? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
       (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
       })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-102559825-1', 'auto');
      ga('send', 'pageview');

    </script>
  <% end %>
</head>
<body>

<%= render "layouts/navigation" if admin_signed_in? %>

<% if admin_signed_in? %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<% end %>

<div class="" id="main-content">
  <div class="left-panel">

    <%= link_to root_path do %>
      <%= image_tag '', class: 'profile-pic' %>
    <% end %>

    <div class="links">
      <div class="profile-name">
        <h1><%= link_to 'Cris R.', root_path %></h1>
      </div>

      <div class="profile-locale">
        <h3><%= locale %></h3>
      </div>

      <div class="social-icons">
        <%= social_links('https://de.linkedin.com/in/crreyes', 'linkedin-square') %>
        <%=  social_links('https://www.xing.com/profile/Cristofer_Reyes', 'xing-square') %>
        <%=  social_links('https://github.com/cristofer', 'github-square') %>

      </div>
    </div>

  </div>

  <div class="right-panel">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, value: f.object.tag_list.to_s, class: "form-control" %>
  </div>

  <div class="form-group">
    <span><%= @tags %></span>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="col-xs-12">
  <div class="text-center">
    <h2><%= post.title %></h2>
    <h6><%= post.created_at.strftime('%d %b, %Y') %></h6>
    <h6><%= render post.tags %></h6>
  </div>

  <div><%=  raw post.body.truncate(50) %></div>

  <div class="text-center">
    <%= link_to t('extras.more'), post_path(post) %>
  </div>

  <% if admin_signed_in? %>
    <%= link_to t('forms.buttons.show'), post_path(post), class: "btn btn-primary" %>
    <%= link_to t('forms.buttons.edit'), edit_post_path(post), class: "btn btn-default" %>
    <%= link_to t('forms.buttons.delete'), post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
  <% end %>

  <hr>

</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<h2>Create a New Post</h2>

<%= render "form" %>

app/views/posts/not_found.html.erb
<div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
  <h2><%= t('not_found') %></h2>
</div>

app/views/posts/show.html.erb
<div class="col-sm-11 col-xs-12 blog-content">
  <h2 class="text-center"><%= @post.title %></h2>
  <h5 class="text-center"><%= @post.created_at.strftime('%d %b, %Y') %></h5>
  <h6 class="text-center"><%= render @post.tags %></h6>

  <br />

  <div><%= raw @post.body %></div>
</div>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= render @posts %></div>